theme:
  default: style-dark
user:
  name: 湘江中路 # Nickname | 昵称
  first_name: 嘉鸿 # 名
  last_name: 陈 # 姓
  email: chenjiahong@datasega.com
  avatar: https://raw.githubusercontent.com/CPeace-creator/picGo/main/logo.jpg?token=AWNON2Q5DKWTIJUXJV55NHTHYLXVG
  describe: 网站简介。 # Describe | 网站简介
  rule_text: 暂不接受个人博客以外的友链申请，确保您的网站内容积极向上，文章至少30篇，原创70%以上，部署HTTPS。 # 友链规则
favicon:
  logo: https://raw.githubusercontent.com/CPeace-creator/picGo/main/logo.jpg?token=AWNON2Q5DKWTIJUXJV55NHTHYLXVG
  show_text: (/≧▽≦/)咦！又好了！
  hide_text: (●—●)喔哟，崩溃啦！
assets:
  third_party_provider: https://npm.elemecdn.com
footer:
  powered:
    enable: true
  beian:
    enable: true
    icp:
  copyright_year:
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 03/01/2025 17:00:00
top_bars:
  - title: About Me
    url: /2025/03/05/home/
  - title: Project
    url: /
    children:
      - title: UniPush推送
        url: /uniPush/
    noswup: true
sidebar:
  typed_text_prefix: I`m
  typed_text: ["Web Developer"]
  info: # 个人信息
    - key: 目标
      val: 独立开发
    - key: 2025目标
      val: 开发课海导航项目
banner:
	danmu: 
		enable: true
		avatar: true
		delayRange: 5000
		speed: 80